### ISSUE TITLE
Change terminal from Macke to termjs

### ISSUE THREAD

**Issue by anant-singh** [cs-education/sysbuild#109]
This was one of the many intended benefits of updating Jor1k so that we could move from the current canvas based terminal emulator implemented by Sebastian to [term.js](https://github.com/chjj/term.js) .

Sebastian has described the process here: [Changing the terminal emulator](https://github.com/s-macke/jor1k/wiki/Changing-terminal-emulator)

**Comment by neelabhg** [comment]
#17 already deals with this.
