### ISSUE TITLE
Add Fall 2015 CS Senior Project team members to this project

### ISSUE THREAD

**Issue by neelabhg** [cs-education/sysbuild#120]
* Create a new team in the cs-education org
* Add to chat room
* Add to PEOPLE.md

**Comment by neelabhg** [comment]
@cmercur2 Why was this closed?

**Comment by cmercur2** [comment]
We were added to the new team in the org, to the chatroom, and are present on the [CREDITS.md](https://github.com/cs-education/sysbuild/blob/master/CREDITS.md) page

**Comment by neelabhg** [comment]
I didn't realize you added the team to credits already. I was going to open a pull request with the necessary changes. Did you push directly to master? I did not see a pull request for this.

When closing issues next time, it'd be great if you could provide some context on why the issue was closed (for example, "fixed in commit xyz", etc).

**Comment by cmercur2** [comment]
Will do in the future! I used the Github markdown editor which pushed directly to master.
