### ISSUE TITLE
JavaScript error in IE 11

### ISSUE THREAD

**Issue by neelabhg** [cs-education/sysbuild#127]
###### Symptoms:
* Virtual machine does not boot
* JavaScript console shows an error

###### Application:
* Link: [staging](http://cs-education.github.io/sys-staging/)
* Built: [Thu Nov 12 2015 06:35:20](https://github.com/cs-education/sys-staging/tree/d9331f44c70dd4549138fefa9aecec37d813ef09)

###### Browser:
* Internet Explorer 11
* Version: 11.11.10586.0
* Update versions: [11.0.25](https://support.microsoft.com/en-us/kb/3100773) (Nov 10, 2015)

###### Operating System:
* Windows 10 Pro 64-bit

###### Console log:
![image](https://cloud.githubusercontent.com/assets/846827/11587627/be28e570-9aa0-11e5-8933-b7444b7ebf8c.png)

**Comment by neelabhg** [comment]
This looks like a Jor1k issue. However, Jor1k's own [compile demo](https://s-macke.github.io/jor1k/demos/compile.html?user=sM8RwaieMQ) (which uses the latest version of Jor1k) seems to work fine in the same browser, so this issue might be fixed once we update our fork of Jor1k.

**Comment by cmercur2** [comment]
It appears this issue has been resolved. Can this be closed?
