### ISSUE TITLE
Captions on lesson videos

### ISSUE THREAD

**Issue by scowalt** [cs-education/sysbuild#71]
Load captions available in [sysassets](https://github.com/angrave/sysassets) and show them as the lesson video is playing.

More information to come.

**Comment by scowalt** [comment]
@neelabhg, could you assign myself and / or @jdtran23 to this issue?

**Comment by scowalt** [comment]
Changed all instances of "subtitles" to "captions" per [this source](https://github.com/videojs/video.js/blob/master/docs/guides/tracks.md)

Some implementation details:
  1. Video captions should be written in WebVTT format
  2. Captions will be stored in and loaded from the sysassets project
  3. Captions would (preferably) not appear overlayed on the video. Code examples often take up all of the screen on the videos, and covering any portion of the screen could prevent viewer understanding.
  4. It may be good to have an option to disable captions

Code should also have fault tolerance,  so that a video will still play if its captions cannot be found or loaded.

Loading these captions from sysassets will require cross-domain requests to be enabled on sysassets, as describe in #70

**Comment by scowalt** [comment]
An isolated (but working) prototype of this exists in [this repository](https://github.com/bobrenjc93/classTranscribe).

One thing this implementation does well is show the previous and upcoming lines along with the current caption. This helps put the material into better context, which will be especially important when users search for terms and potentially start in the middle of videos.

Before much more progress can be made on this issue, the transcripts need to be added to the sysassets project in the WebVTT format. This is a work in progress.

**Comment by scowalt** [comment]
There is a poorly-documented method of adding captions (or text tracks) from a remote source in videojs (here)[http://docs.brightcove.com/en/perform/brightcove-player/guides/adding-captions-to-videos.html]. There is also at least one library to help add captions to videojs, although I would prefer not to add another dependency to the project.

**Comment by scowalt** [comment]
An issue I'm running into now is that getting a remote track with videojs doesn't work with xdomain. (the videojs library expects CORS headers)

I believe this is caused by the fact that videojs implements [its own http request module](https://github.com/videojs/video.js/blob/master/src/js/xhr.js). I may need to make a pull request on videojs or xdomain to fix this issue. I hope that we won't have to use a custom build of either library or do a complicated hack.

**Comment by scowalt** [comment]
The issue I described in my [previous comment](https://github.com/cs-education/sysbuild/issues/71#issuecomment-83737216) has magically disappeared.

The completion of this issue is currently blocked by [an issue with sysassets](https://github.com/cs-education/sysassets/issues/7)

**Comment by angrave** [comment]
On 4/1/15 3:36 PM, Scott Walters wrote:
>
> The issue I described in my previous comment 
> <https://github.com/cs-education/sysbuild/issues/71#issuecomment-83737216> 
> has magically disappeared.
>
> The completion of this issue is currently blocked by an issue with 
> sysassets <https://github.com/cs-education/sysassets/issues/7>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cs-education/sysbuild/issues/71#issuecomment-88624269>.
>
Re. magically dissappeared -> because we moved sysassets to cs-education ?

**Comment by scowalt** [comment]
Actually I don't think that was the cause.

Basically, my issue was that the request for the remote caption track (made by videojs) wasn't being routed through xdomain. Thus, I was getting the CORS errors that led us to use xdomain in the first place.

However, today I went to reproduce the error, and this issue was no longer present. The request for the transcripts is now being routed through xdomain as expected.

In both of these instances I was/am testing using my personal fork of sysassets, at http://scowalt.github.io/sysassets, so I don't think the domain switch of sysassets was the cause.

**Comment by scowalt** [comment]
I did a bit of research on using [videojs-caption](http://sampingchuang.com/videojs-caption) as a library to help with moving the subtitles out of the video player. However, using this library would require us to modify our subtitles out of the WebVTT format and into something less universal.

**Comment by angrave** [comment]
If you haven't already, you could ask Bob(jren4) how he implemented the subtitles on the system programming videos at http://classtranscribe.com
