### ISSUE TITLE
Provide link to systems programming book

### ISSUE THREAD

**Issue by scowalt** [cs-education/sysbuild#74]
Provide a link to [this crowd-sourced systems programming book](https://github.com/angrave/SystemProgramming/wiki) somewhere in the interface (maybe the navbar?). Might be nice to embed this page or open it in a new window so as not to direct people away from the site.

**Comment by neelabhg** [comment]
The book is a GitHub wiki. After discussion with @anant-singh, there are a few ways of embedding the GitHub wiki into the application:
* `iframe`s are not allowed, as GitHub sets the `X-Frame-Options` to `deny`
* Use some build process to pull the wiki's git repository (GitHub wiki's are essentially git repositories) and serve them from [sysassets](https://github.com/cs-education/sysassets).
* Similar to above, but include the wiki git repository as a git `submodule` or `subtree` in sysassets. The downside of the above two approaches is that the copy served will become old soon - regular deployments will be needed to incorporate changes in the wiki.
* Have a server backend which fetches a wiki page and serves it when requested through an API. The downside is that we'll have to maintain a service.

The above approaches are outside the scope of the Spring 2015 senior project course, and so currently all we'll do is include a link to the book in the navbar which will open in a new browser tab.

**Comment by anant-singh** [comment]
Yeah, I realized the same and waiting for confirmation but seeing your latest commit I guess you added the link in the page so thanks. I guess you can close this issue also. Maybe we can reopen it again if anything changes.
