### ISSUE TITLE
Make play button more obvious

### ISSUE THREAD

**Issue by scowalt** [cs-education/sysbuild#75]
Currently, the play button in the user interface isn't very prominent and its purpose isn't very clear. It may also be helpful to have an animation or other indicator when the VM becomes ready and the button goes from grayed out to green. This will make for a simpler user experience.

**Comment by neelabhg** [comment]
See @scowalt's [comment](https://github.com/cs-education/sysbuild/pull/80#issuecomment-77488797) for an idea for the play button's design.
